services:
  postgres:
    image: postgres:16
    container_name: go-clean-postgres
    restart: always
    environment:
      POSTGRES_USER: go_user
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: go_clean_api
    ports:
      - "5431:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: